# Generated by Django 3.0.8 on 2020-07-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='codigo_acao',
            new_name='papel',
        ),
    ]
