# Generated by Django 3.0.8 on 2020-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acao', models.CharField(max_length=8)),
                ('data_atualizacao', models.DateTimeField()),
                ('preco_atual', models.FloatField()),
                ('tipo', models.CharField(max_length=5)),
            ],
        ),
    ]
