# Generated by Django 3.0.8 on 2020-07-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papel',
            name='historico_completo',
            field=models.BooleanField(default=False),
        ),
    ]
