# Generated by Django 3.0.8 on 2020-07-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('abertura', models.FloatField()),
                ('fechamento', models.FloatField()),
                ('maximo', models.FloatField()),
                ('minimo', models.FloatField()),
                ('volume', models.FloatField()),
                ('codigo_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papel.Papel')),
            ],
        ),
    ]
