# Generated by Django 3.0.8 on 2020-07-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='volume',
            new_name='media',
        ),
    ]
