# Generated by Django 3.0.8 on 2020-07-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negociacoes',
            old_name='preco_medio',
            new_name='preco_medio_total',
        ),
        migrations.AddField(
            model_name='negociacoes',
            name='preco_medio_unitario',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
