# Generated by Django 3.0.8 on 2020-07-22 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papel', '0002_papel_historico_completo'),
        ('negociacoes', '0002_auto_20200721_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='negociacoes',
            name='papel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papel.Papel'),
            preserve_default=False,
        ),
    ]
