# Generated by Django 3.0.8 on 2020-07-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negociacoes', '0003_negociacoes_papel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negociacoes',
            name='compra',
        ),
    ]
