# Generated by Django 3.0.8 on 2020-07-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('taxa_acoes', models.FloatField()),
                ('taxa_fiis', models.FloatField()),
                ('taxa_etfs', models.FloatField()),
            ],
        ),
    ]
